Diary/config/routes.rb
Rails.application.routes.draw do
	resources :entries
	root to: 'entries#index'
end

Diary/app/models/entry.rb
class Entry < ActiveRecord::Base
	# Validations
	validates :title, length: { minimum: 1, maximum: 255 }
	validates :description, length: { minimum: 1, maximum: 4096 }
	validates :author, length: { minimum: 1, maximum: 4 }
	validates :author, inclusion: { in: %w( Rosa Ines ) }
end

Diary/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	before_action :authenticate, only: [:new, :create, :edit, :update, :destroy]
	

	
private
	def entry_params
	  params.require(:entry).permit(:title, :description, :author)
	end

	def authenticate
		authenticate_or_request_with_http_basic do |u,p|
			u == 'Rosa' && ActiveSupport::SecurityUtils.secure_compare(p, 'banana') || 
			u == 'Ines' && ActiveSupport::SecurityUtils.secure_compare(p, 'morango')
		end
	end

public
	def index
		@entries = Entry.order(created_at: :desc).all
	end

	def new
		@entry = Entry.new
	end

	def create
		@entry = Entry.new(entry_params)
		if @entry.save
			puts "oi1"
			UserMailer.welcome_email(@entry.title,@entry.author, @entry.description).deliver_now
			puts "oi2"
			redirect_to entries_path
		else
			render :new
		end
	end



	def edit
		@entry = Entry.find(params[:id])
	end

	def update
		@entry = Entry.find(params[:id])
		@entry.update(entry_params)
		redirect_to entries_path
	end

	def destroy
		@entry = Entry.find(params[:id])
		@entry.delete
		redirect_to entries_path
	end


end

Diary/app/views/admin/index.html.erb
<div  ="header">
	<div class="container">
	<h1>DEIGirls Diary</h1>
	</div>
</div>
<div class="main">
	<div class="container">
		<h2> New entry </h2><br>
		<%= form_for(@new_entry) do |f| %>
			<div class="field"> 
				<%= f.label :Title %>        
					<%= f.text_area :title %><br> 
				<%= f.label :Description %>  
					<%= f.text_area :description %> <br>
				<%= f.label :By %>           
					<%= f.text_area :author %> <br>
			</div> 
			<div class="actions"> 
				<%= f.submit "Post" %> 
			</div> 
		<% end %>
	</div>

	<div class="container">
		<h2>Past entries</h2>
		<table style="width:100%">
			<td>Author</td>
			<td>Date</td>
			<td>Title</td>
			<td>Description</td>
			<td>Update</td>
			<td>Delete</td>
			<ul class="comments">
				<% @all_entries.each do |p| %>
					<tr>
						<td><%=p.author%></td>
						<td><%=p.created_at %></td>
						<td><%=p.title %></td>
						<td><%= p.description%></td>
						<td></td>
						<td></td>
					</tr>
				<% end %>
			</ul> 
        </table> 
    </div>
</div>

Diary/app/views/entries/_entry.html.erb
<h3><%= entry.title %></h3>
<p><%= entry.created_at %> by <%= entry.author %></p>
<p><%= entry.description%> </p>
<%= link_to 'Delete this', entry_path(entry), method: :delete, data: { confirm: 'Really? '} %>
<%= link_to 'Update this', edit_entry_path(entry)%>

Diary/app/views/entries/edit.html.erb
<div  ="header">
	<div class="container">
	<h1>DEIGirls Diary</h1>
	</div>
</div>
<div class="main">
	<div class="container">
		<h2> New entry </h2><br>
		<%= form_for(@entry) do |f| %>
			<div class="field"> 
				<%= f.label :title %><br>
					<%= f.text_area :title %><br><br>
				<%= f.label :description %><br>
					<%= f.text_area :description %> <br><br>
				<%= f.label :author %><br>
					<%= f.text_area :author %> <br><br>
			</div> 
			<div class="actions"> 
				<%= f.submit "Update" %> 
			</div> 
		<% end %>
	</div>
</div>

Diary/app/views/entries/index.html.erb
    <div class="header">
      <div class="container">
        <h1>DEIGirls Diary</h1>
        <%= link_to 'Add entry', new_entry_path %>
      </div>
    </div>

    <div class="main">
      <div class="container">
        <ul class="comments">
          <%= render partial: 'entries/entry', collection: @entries %>
        </ul>
     </div>

Diary/app/views/entries/new.html.erb
<div  ="header">
	<div class="container">
	<h1>DEIGirls Diary</h1>
	</div>
</div>
<div class="main">
	<div class="container">
		<h2> New entry </h2><br>
		<%= form_for(@entry) do |f| %>
			<%= f.object.errors.full_messages.join(', ') %>

			<div class="field">
				<%= f.label :title %> <br>
					<%= f.text_field :title %> <br><br>
				<%= f.label :description %> <br>
					<%= f.text_area :description %> <br><br>
				<%= f.label :author %> <br>
					<%= f.select(:author, ['Ines', 'Rosa'], :selected => "Ines") %> <br><br>
			</div>
			<div class="actions">
				<%= f.submit "Add" %>
			</div>
		<% end %>
	</div>
</div>